// 首页轮播图icon
const lbData = [
  [
    {
      'img':'../../../static/inster/meishi.png',
      'title':'美食'
    },
    {
      'img':'../../../static/inster/chaoshi.png',
      'title':'超市便利'
    },
    {
      'img':'../../../static/inster/shuiguo.png',
      'title':'蔬菜水果'
    },
    {
      'img':'../../../static/inster/meituan.png',
      'title':'美团专送'
    },
    {
      'img':'../../../static/inster/paotui.png',
      'title':'跑腿代购'
    },
    {
      'img':'../../../static/inster/yexiao.png',
      'title':'夜宵'
    },
    {
      'img':'../../../static/inster/jintie.png',
      'title':'津贴联盟'
    },
    {
      'img':'../../../static/inster/pinping.png',
      'title':'甜点饮品'
    },
    {
      'img':'../../../static/inster/shaokao.png',
      'title':'龙虾烧烤'
    },
    {
      'img':'../../../static/inster/dangao.png',
      'title':'甜蜜蛋糕'
    }
  ],
  [
    {
      'img':'../../../static/inster/hanbao.png',
      'title':'汉堡披萨'
    },
    {
      'img':'../../../static/inster/liaoli.png',
      'title':'日韩料理'
    },
    {
      'img':'../../../static/inster/malatang.png',
      'title':'麻辣烫'
    },
    {
      'img':'../../../static/inster/kuaican.png',
      'title':'快食简餐'
    },
    {
      'img':'../../../static/inster/xianhua.png',
      'title':'浪漫鲜花'
    },
    {
      'img':'../../../static/inster/lazi.png',
      'title':'无辣不欢'
    },
    {
      'img':'../../../static/inster/jiaozi.png',
      'title':'饺子馆'
    },
    {
      'img':'../../../static/inster/xiaochi.png',
      'title':'小吃馆'
    },
    {
      'img':'../../../static/inster/baofan.png',
      'title':'煲仔饭'
    },
    {
      'img':'../../../static/inster/qita.png',
      'title':'其他'
    }
  ]
]

export {
  lbData 
}